library identifier: 'docker-pipelines-library@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/JaimeSalas/docker-pipelines-library.git'])

pipeline {
    agent any 
    stages {
        stage('Audit Tools') {
            steps {
                auditTools() 
            }
        }
    }
}
