FROM node:14.15.4-buster 

WORKDIR /opt/app

COPY ./db/migrations ./db/migrations 

COPY ./knexfile.js ./knexfile.js 

COPY ./wait-for-it.sh ./wait-for-it.sh 

RUN chmod +x wait-for-it.sh 

RUN npm init -y 

RUN npm i knex@0.21.16 pg@8.5.1 dotenv@8.2.0

