pipeline {
    agent any 

    stages {
        stage('audit tools') {
            steps {
                sh ''' 
                    docker -v 
                    docker-compose -v 
                '''
            }
        }
        stage('unit test') {
            agent {
                docker {
                    image 'node:14.15.4-buster'
                }
            }
            steps {
                dir('integration-tests/hangman-back/') {
                    sh '''
                        npm ci 
                        npm test
                    '''
                }
            }
        }
        stage('integration test') {
            steps {
                dir('integration-tests/hangman-back/') {
                    // sh 'docker-compose -f test-integration.yml up --exit-code-from test-integration'
                    sh 'docker-compose -f test-integration.yml up -d'
                    script {
                        def status = sh(script: 'docker wait test-integration', returnStdout: true)
                        println status
                    }
                }
            }
        }
    }
    
    post {
        always {
            echo 'clean reources'
            sh '''
                cd 'integration-tests/hangman-back/'
                docker-compose -f test-integration.yml down --rmi all -v
            '''
            cleanWs()
        }
    }
}
