pipeline {
    agent {
        docker {
            image 'jaimesalas/node-builder:1'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh '''
                    node --version
                    npm version
                '''
                sh 'printenv'
            }
        }
        stage('Build') {
            steps {
                dir("$WORKSPACE/todo-app") {
                    sh '''
                        npm install
                        npm run build 
                    '''
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir("$WORKSPACE/todo-app") {
                    sh 'npm test'
                }
            }
        }
    }
}
