pipeline {
    agent {
        docker {
            dir 'different-workflows'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh '''
                    node --version
                    npm version
                '''
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t jaimesalas/session-docker-pipeline:0.0.1'
            }
        }
        stage('Smoke Test') {
            steps {
                sh 'docker run jaimesalas/session-docker-pipeline:0.0.1'
            }
        }
    }
}
