library identifier: 'docker-pipelines-library@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/JaimeSalas/docker-pipelines-library.git'])


pipeline {
    agent any 

    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is RC?')
    }
    
    environment {
        VERSION  = sh([ script: 'cd ./todo-app && npx -c \'echo $npm_package_version\'', returnStdout: true ]).trim();
        VERSION_RC = "rc.2"
        // VERSION_RC = 'rc.2"
    }
    
    stages {
        stage('Audit Tools') {
            steps {
                auditTools()
            }
        }
        stage('Build') {
            environment {
                VERSION_SUFFIX = getVersionSuffix rcNumber: env.VERSION_RC, isReleaseCandidate: params.RC
            }
            steps {
                dir('./todo-app') {
                    echo "Building version ${VERSION} with suffix: ${VERSION_SUFFIX}"
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('./todo-app') {
                    sh 'npm test'
                }
            }
        }
        stage('Publish') {
            when {
                expression { return params.RC }
            }
            steps {
                archiveArtifacts('todo-app/app/')
            }
        }
    }    
}
