pipeline {
    agent any 

    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is RC?')
    }
    
    environment {
        VERSION  = sh([ script: 'cd ./todo-app && npx -c \'echo $npm_package_version\'', returnStdout: true ]).trim();
        VERSION_RC = "rc.2"
    }
    
    stages {
        stage('Audit Tools') {
            steps {
                sh '''
                    git version
                    docker version
                    node --version
                    npm version
                '''
            }
        }
        stage('Build') {
            environment {
                VERSION_SUFFIX = sh(script: 'if [ "${RC}" == "true" ] ; then echo -n "${VERSION_RC}+ci.${BUILD_NUMBER}"; else echo -n "${VERSION_RC}"; fi', returnStdout: true)
            }
            steps {
                dir('./todo-app') {
                    echo "Building version ${VERSION} with suffix: ${VERSION_SUFFIX}"
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('./todo-app') {
                    sh 'npm test'
                }
            }
        }
        stage('Publish') {
            when {
                expression { return params.RC }
            }
            steps {
                sh '''
                    cd todo-app 
                    ls -al 
                '''
                // archiveArtifacts('./todo-app/app')
            }
        }
    }
    
}
