def image 

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    image = docker.build("jaimesalas/todo-app-dc-pipelines:1", "--pull -f todo-app/Dockerfile todo-app")           
                }
            }
        }
        stage('Smoke Test') {
            steps {
                script {
                    container = image.run()
                    container.stop()
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    withDockerRegistry([credentialsId: "docker-hub", url: ""]) {
                        image.push()
                    }
                }
            }
        }
    }
}
