pipeline {
    agent any 
    
    environment {
        RELEASE  = '0.0.1'
    }
    
    stages {
        stage('Build') {
            agent any 
            environment {
                LOG_LEVEL='INFO'
            }
            parallel { // [1, 2][1, 2, 3]
                stage('linux-arm64') {
                    echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
                }
                stage('linux-amd64') {
                    echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
                }
                stage('windows-amd64') {
                    echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}..."
            }
        }
        stage('Deploy') {
            // node none
            input {
                message 'Deploy?'
                ok 'Do it'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
                }
            }
            steps {
                echo "Deploying release ${RELEASE} to ${TARGET_ENVIRONMENT}"
            }
        }
    }
    
    post {
        always {
            echo "print always"
        }
    }
}
